name: 'Code Review'
description: 'Generate prompt for code review'
inputs:
  REVIEW_DATA:
    description: ""
    required: true
  PR_NUMBER: # id of input
    description: ""
    required: true
  GITHUB_TOKEN:
    description: ""
    required: true
runs:
  using: "composite"
  steps:

  - name: Set up Python
    uses: actions/setup-python@v5
    with:
      python-version: '3.11'

  - name: Install dependencies
    shell: bash
    run: |
      python -m pip install --upgrade pip
      pip install PyGithub # requests

  - name: Set GitHub Path
    run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
    shell: bash
    env:
      GITHUB_ACTION_PATH: ${{ github.action_path }}

  - name: Process JSON files
    shell: bash
    env:
      API_URL: ${{ secrets.API_URL }}
    run: python ${{ github.action_path }}apply_code_review.py "${{ github.event.inputs.REVIEW_DATA }}"

