name: 'Code Review'
description: 'Generate prompt for code review'
inputs:
  PR_NUMBER:  # id of input
    description: ""
    required: true
  GITHUB_TOKEN:
    description: ""
    required: true
#outputs:
#  random-number:
#    description: "Random number"
#    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v4
    with:
      fetch-depth: 0

  - name: Get changed files
    id: changed-files
    uses: tj-actions/changed-files@v44

  - name: Set up Python
    uses: actions/setup-python@v5
    with:
      python-version: '3.11'

  - name: Install dependencies
    shell: bash
    run: |
      python -m pip install --upgrade pip
      pip install PyGithub # requests

  - name: Set GitHub Path
    run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
    shell: bash
    env:
      GITHUB_ACTION_PATH: ${{ github.action_path }}

  - name: Run Code Review
    env:
#      REVIEW_API_URL: some_url #${{ secrets.REVIEW_API_URL }}
#      REVIEW_API_KEY: some_api_ket #${{ secrets.REVIEW_API_KEY }}
      PR_NUMBER: ${{inputs.PR_NUMBER}} #${{ github.event.number }}
      GITHUB_TOKEN: ${{inputs.GITHUB_TOKEN}} #${{ secrets.GITHUB_TOKEN }}
    shell: bash
    run: |
      echo '${{ steps.changed-files.outputs.all_changed_files }}'
      python code_review.py '${{ steps.changed-files.outputs.all_changed_files }}'

