name: Bump version

on:
  workflow_call:
    inputs:
      bump_type:
        description: 'Bump type'
        required: true
        default: 'patch'
        type: string
#        options:
#        - patch
#        - minor
#        - major
#      create_tag:
#        description: "create tag"
#        required: false
#        type: boolean
#        default: false
#      labels:
#        description: "Labels for the PR. Comma or newline-separated list."
#        required: false
#        type: string
#        default: ""
#      assignees:
#        description: "Assignees for the PR. Comma or newline-separated list of GitHub usernames."
#        required: false
#        type: string
#        default: ""

#1.9.2 ── bump ─┬─ major ─ 2.0.0-dev0
#               ├─ minor ─ 1.10.0-dev0
#               ├─ patch ─ 1.9.3-dev0
#               ├─ pre_l ─ invalid: The part has already the maximum value among ['dev', 'final'] and cannot be bumped.
#               ╰─ pre_n ─ 1.9.2-final1


#1. after release bump patch -> 1.9.3-dev0
#1.9.3-dev0 ── bump ─┬─ major ─ 2.0.0-dev0
#                    ├─ minor ─ 1.10.0-dev0
#                    ├─ patch ─ 1.9.4-dev0
#                    ├─ pre_l ─ 1.9.3
#                    ╰─ pre_n ─ 1.9.3-dev1

#2. final release:
#  1.9.3-dev0 -> 2.0.0: bump major, bump pre_l
#  1.9.3-dev0 -> 1.10.0: bump minor, bump pre_l
#  1.9.3-dev0 -> 1.9.3: bump pre_l
#
#2b. pre-release: 1.9.3-dev0 -> 1.9.3-dev1: bump pre_n

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Bump version
        id: bump
        uses: callowayproject/bump-my-version@master
        env:
          BUMPVERSION_TAG: "false"
        with:
          args: ${{ inputs.bump_type }}
          branch: bump-version
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create a pull request
        id: create-pull-request
        if: steps.bump.outputs.bumped == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          branch: bump-version #"bump-version-${{ steps.bump.outputs.current-version }}"
          title: "[VERSION] Bump version to ${{ steps.bump.outputs.current-version }}"
          body: "Bump the version to ${{ steps.bump.outputs.current-version }} (from previous version ${{ steps.bump.outputs.previous-version }}). Autogenerated by alphashared workflow."
#          labels: ${{ inputs.labels }}
#          assignees: ${{ inputs.assignees }}
          delete-branch: true

#      - name: Create tag
#        if: steps.bump.outputs.bumped == 'true'
#        uses: actions/github-script@v5
#        with:
#          script: |
#            github.rest.git.createRef({
#              owner: context.repo.owner,
#              repo: context.repo.repo,
#              ref: 'refs/tags/v${{ steps.bump.outputs.current-version }}',
#              sha: '${{ steps.create-pull-request.outputs.pull-request-head-sha }}'
#            })

      - name: Check
        if: steps.bump.outputs.bumped == 'true'
        run: |
          echo "Version was bumped from ${{ steps.bump.outputs.previous-version }} to ${{ steps.bump.outputs.current-version }}"