name: Code Review

on:
  pull_request:
    types: [ labeled ]

jobs:
  code-review:
    runs-on: ubuntu-latest
    #if: contains(github.event.pull_request.labels.*.name, 'review')
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
