# Update the frozen requirements file and create a pull request with the changes.
# Assumes that requirements files are in a directory called `requirements`.
name: Update requirements

on:
  workflow_call:
    inputs:
      requirements_file_name:
        description: 'Requirements file name'
        required: true
        type: string
      branch_name:
        description: 'Name of branch to update requirements'
        type: string
        default: "main"
        required: false
      python_version:
        description: 'Python version, e.g. 3.11'
        required: false
        default: '3.11'
        type: string

jobs:
  update-requirements:
    name: Update requirements
    runs-on: ubuntu-latest
    env:
      UV_VERSION: 0.5.31
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{inputs.branch_name}}

      - name: Set up git config
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com"
          git config --global user.name "$(gh api /users/${GITHUB_ACTOR} | jq .name -r)"
          git config -l

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{inputs.python_version}}

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: ${{env.UV_VERSION}}

      - name: Update requirements
        id: update_requirements
        run: |
          CURRENT_DATE=$(date '+%Y-%m-%d_%H-%M-%S')
          FILE_NAME=${{inputs.requirements_file_name}}
          FREEZE_FILE_NAME=_${FILE_NAME/.txt/.freeze.txt}
          
          cd requirements
          
          uv venv --python ${{inputs.python_version}}
          
          # in case we update e.g. "requirements_gui.txt", we want the resulting requirements to be compatible with the other frozen requirements file
          # TODO this could be tricky if one had three flavours..
          if [[ $FILE_NAME == *"_"* ]]; then
            uv pip install -r $FILE_NAME --constraint _requirements.freeze.txt
          else
            uv pip install -r $FILE_NAME
          fi
          
          
          echo "# Autogenerated by alphashared workflow. Do not edit manually! Last update: $CURRENT_DATE" > $FREEZE_FILE_NAME
          uv pip freeze >> $FREEZE_FILE_NAME
          
          # add constraints
          CONSTRAINTS_FILE_NAME=${FILE_NAME/.txt/.constraints.txt}
          if [ -f $CONSTRAINTS_FILE_NAME ]; then
            while IFS= read -r line; do
              # skip comment lines
              if [[ "$line" =~ ^# ]] || [[ -z "$line" ]]; then
                continue
              fi

              # Extract the part before and after the `-->`
              before=$(echo "$line" | awk -F'-->' '{print $1}')
              after=$(echo "$line" | awk -F'-->' '{print $2}')
            
              # Search for the part before `-->` in the search file
              if grep -q "$before" "$FREEZE_FILE_NAME"; then
                # Append the part after `-->` to the matching line in the search file
                sed -i "/$before==/ s/$/ $after/" "$FREEZE_FILE_NAME"
              fi
            done < "$CONSTRAINTS_FILE_NAME"
          fi
          
          git add $FREEZE_FILE_NAME
          git commit -m "Updating ${FREEZE_FILE_NAME}"
          
          echo CURRENT_DATE=$CURRENT_DATE >> $GITHUB_OUTPUT
          echo NEW_BRANCH_NAME=update_${{inputs.requirements_file_name}}_${CURRENT_DATE} >> $GITHUB_OUTPUT

      - name: Push changes to GitHub
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{steps.update_requirements.outputs.NEW_BRANCH_NAME}}
          # no force push: fail if branch already exists

      - name: Create a pull request
        id: create-pull-request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ${{ inputs.branch_name }}
          branch: ${{steps.update_requirements.outputs.NEW_BRANCH_NAME}}
          title: "[REQUIREMENTS] Update ${{inputs.requirements_file_name}}"
          body: "Update ${{inputs.requirements_file_name}}. Autogenerated by alphashared workflow."
          delete-branch: true