# Update the frozen requirements file and create a pull request with the changes.
# Assumes that requirements files are in a directory called `requirements`.
name: Update requirements

on:
  workflow_call:
    inputs:
      requirements_file_name:
        description: 'Requirements file name'
        required: true
        type: string
      branch_name:
        description: 'Name of branch to update requirements'
        type: string
        default: "main"
        required: false
      python_version:
        description: 'Python version, e.g. 3.11'
        required: false
        default: '3.11'
        type: string

jobs:
  update-requirements:
    name: Update requirements
    runs-on: ubuntu-latest
    env:
      UV_VERSION: 0.5.31
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{inputs.branch_name}}

      - name: Set up git config
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com"
          git config --global user.name "$(gh api /users/${GITHUB_ACTOR} | jq .name -r)"
          git config -l

      - name: Set GitHub Path
        run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
        shell: bash
        env:
          GITHUB_ACTION_PATH: ${{ github.action_path }}

      - name: Set up env
        id: setup_env
        run: |
          CURRENT_DATE=$(date '+%Y-%m-%d_%H-%M-%S')
          FILE_NAME=${{inputs.requirements_file_name}}
          FREEZE_FILE_NAME=_${FILE_NAME/.txt/.freeze.txt}

          echo NEW_BRANCH_NAME=update_${{inputs.requirements_file_name}}_${{steps.update_requirements.outputs.CURRENT_DATE}} >> $GITHUB_OUTPUT
          echo CURRENT_DATE=$CURRENT_DATE >> $GITHUB_OUTPUT
          echo FREEZE_FILE_NAME=$FREEZE_FILE_NAME >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and export
        uses: docker/build-push-action@v6
        with:
          tags: update_requirements:latest
          context: ${{ github.action_path }}/update_requirements
          outputs: type=docker,dest=/tmp/update_requirements.tar
          build-args: |
            PYTHON_VERISON=${{ inputs.python_version }}
            REQUIREMENTS_FILE_NAME=${{ inputs.requirements_file_name }}
            UV_VERSION=${{ env.UV_VERSION }}
            CURRENT_DATE=${{ steps.setup_env.outputs.CURRENT_DATE }}
            FREEZE_FILE_NAME=${{ steps.setup_env.outputs.FREEZE_FILE_NAME }}


      - name: Load image
        run: |
          docker load --input /tmp/update_requirements.tar
          docker image ls -a
      - name: Update requirements
        run: |
          docker run -v ./requirements/:/app/output -t update_requirements
          
          cd requirements
          git add $FREEZE_FILE_NAME
          git commit -m "Updating ${FREEZE_FILE_NAME}"


      - name: Push changes to GitHub
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{steps.setup_env.outputs.NEW_BRANCH_NAME}}
          # no force push: fail if branch already exists

      - name: Create a pull request
        id: create-pull-request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ${{ inputs.branch_name }}
          branch: ${{steps.setup_env.outputs.NEW_BRANCH_NAME}}
          title: "[REQUIREMENTS] Update ${{inputs.requirements_file_name}}"
          body: "Update ${{inputs.requirements_file_name}}. Autogenerated by alphashared workflow."
          delete-branch: true