name: Update requirements

on:
  workflow_call:
#    inputs:
#      bump_type:
#        description: 'Bump type'
#        required: true
#        default: 'patch'
#        type: string

jobs:
  update-requirements:
    name: Update requirements
    runs-on: ubuntu-latest
    env:
      UV_VERSION: 0.5.31
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/${{env.UV_VERSION}}/install.sh | sh

      - name: Setting up git config
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com"
          git config --global user.name "$(gh api /users/${GITHUB_ACTOR} | jq .name -r)"
          git config -l

      - name: Get branch name
        id: get_branch_name
        run: |
          echo BRANCH_NAME=update_requirements_$(date | tr " :" "-") >> $GITHUB_OUTPUT

      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pip cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}

      - name: Update requirements
        run: |
          cd requirements
          FILE_NAME=requirements
          uv venv --python 3.11
          uv pip install -r $FILE_NAME.txt
          uv pip freeze > _${FILE_NAME}.freeze.txt
          git add _${FILE_NAME}.freeze.txt
          git commit -m "Updating _${FILE_NAME}.freeze.txt"


      - name: Push changes to GitHub
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{steps.get_branch_name.outputs.BRANCH_NAME}}
          # no force push: fail if branch already exists

      - name: Create a pull request
        id: create-pull-request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          branch: ${{steps.get_branch_name.outputs.BRANCH_NAME}}
          title: "[REQUIREMENTS] Update requirements"
          body: "Update requirements. Autogenerated by alphashared workflow."
          delete-branch: true